services:
  bot:
    build: .
    container_name: discord-bot
    restart: unless-stopped
    environment:
      DISCORD_TOKEN:
      REPORT_CHANNEL_ID:
      NITRADO_API_TOKEN:
      NITRADO_SERVICE_ID:
      FTP_HOST:
      FTP_PORT:
      FTP_USER:
      FTP_PASS:
      SAVE_SLOT:
