services:
  bot:
    build: .
    container_name: discord-bot
    restart: unless-stopped
    environment:
      DISCORD_TOKEN:
      REPORT_CHANNEL_ID:
      NITRADO_API_TOKEN:
      NITRADO_SERVICE_ID:
    volumes:
      - /var/lib/docker/volumes/fs25-server_config/_data


