services:
  bot:
    build: .
    container_name: discord-bot
    restart: unless-stopped
    environment:
      DISCORD_TOKEN:
      REPORT_CHANNEL_ID:
      NITRADO_API_TOKEN:
      NITRADO_SERVICE_ID:
    volumes:
      - config:/opt/fs25/config

