services:
  bot:
    build: .
    container_name: discord-bot
    restart: unless-stopped
    environment:
      DISCORD_TOKEN:
      REPORT_CHANNEL_ID:
      WEB_URL:
      WEB_USER:
      WEB_PASS:
    volumes:
      - /var/lib/docker/volumes/fs25-server_config/_data:/fs25_save





